name: HACS
on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5  # v4.3.1
      - uses: hacs/action@d556e736723344f83838d08488c983a15381059a  # 22.5.0
        with:
          category: integration
